# "This weeks fun with jetson-nano"
> "Awesome summary"

- toc: false
- branch: master
- badges: true
- comments: true
- categories: [fastpages, jupyter]
- image: images/some_folder/your_image.png
- hide: false
- search_exclude: true
- metadata_key1: metadata_value1
- metadata_key2: metadata_value2

In [1]:
# Ok i have pytorch - cuda - all setup    ...I think

from __future__ import print_function
import torch
print(torch.__version__)

1.6.0


In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4901, 0.3544, 0.7686],
        [0.1711, 0.2013, 0.3388],
        [0.7860, 0.1084, 0.5414],
        [0.7518, 0.5457, 0.6297],
        [0.1423, 0.7226, 0.4924]])


In [3]:
# Construct a matrix filled with zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
# Construct a tensor directly from data:

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
import cv2 
print(cv2.__version__)

4.1.1


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)       # result has the same size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.6440, -0.3136, -0.0883],
        [ 0.7964,  0.1387,  0.2667],
        [ 0.4095, -0.6831, -0.5344],
        [ 0.7091, -0.9569, -0.0085],
        [-2.1491, -0.7399, -0.2826]])
torch.Size([5, 3])


In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.1354,  0.5886,  0.7330],
        [ 1.5919,  0.3085,  0.4636],
        [ 0.5622, -0.0884,  0.4141],
        [ 1.7086, -0.0870,  0.6953],
        [-1.4914,  0.2235,  0.1822]])


In [8]:
# more ways to do addition: syntax 2
print(torch.add(x, y))

tensor([[ 2.1354,  0.5886,  0.7330],
        [ 1.5919,  0.3085,  0.4636],
        [ 0.5622, -0.0884,  0.4141],
        [ 1.7086, -0.0870,  0.6953],
        [-1.4914,  0.2235,  0.1822]])


In [9]:
# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.1354,  0.5886,  0.7330],
        [ 1.5919,  0.3085,  0.4636],
        [ 0.5622, -0.0884,  0.4141],
        [ 1.7086, -0.0870,  0.6953],
        [-1.4914,  0.2235,  0.1822]])


In [10]:
# Addition x to y 
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.1354,  0.5886,  0.7330],
        [ 1.5919,  0.3085,  0.4636],
        [ 0.5622, -0.0884,  0.4141],
        [ 1.7086, -0.0870,  0.6953],
        [-1.4914,  0.2235,  0.1822]])


In [11]:
# NOTE

# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

# You can use standard NumPy-like indexing with all bells and whistles!

print(x[:, 1])

tensor([-0.3136,  0.1387, -0.6831, -0.9569, -0.7399])


In [12]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5727])
0.5727261304855347


In [14]:
# Read later:

# 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described here.
# NumPy Bridge
# Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

# The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [18]:
# CUDA Tensors  

# Tensors can be moved onto any device using the .to method.
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.5727], device='cuda:0')
tensor([1.5727], dtype=torch.float64)
