# "This weeks fun with jetson-nano"
> "Awesome summary"

- toc: false
- branch: master
- badges: true
- comments: true
- categories: [fastpages, jupyter]
- image: images/some_folder/your_image.png
- hide: false
- search_exclude: true
- metadata_key1: metadata_value1
- metadata_key2: metadata_value2

In [1]:
# Ok i have pytorch - cuda - all setup    ...I think

from __future__ import print_function
import torch
print(torch.__version__)

1.5.0


In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-9.3657e-35,  1.7796e-43,  7.0066e-15],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.7275e-43,  1.2349e-39,  6.5940e-15],
        [ 0.0000e+00,  6.5940e-15,  0.0000e+00],
        [ 1.5975e-43,  0.0000e+00,  1.6675e-43]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4901, 0.3544, 0.7686],
        [0.1711, 0.2013, 0.3388],
        [0.7860, 0.1084, 0.5414],
        [0.7518, 0.5457, 0.6297],
        [0.1423, 0.7226, 0.4924]])


In [4]:
# Construct a matrix filled with zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Construct a tensor directly from data:

x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
import cv2 
print(cv2.__version__)

4.3.0


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)       # result has the same size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0515, -2.7662, -0.1933],
        [-1.1136,  0.9000,  0.8919],
        [ 1.5397,  2.2545, -1.8473],
        [-0.0747, -1.0172, -0.4092],
        [-1.1937,  0.0291,  0.2559]])
torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4943, -1.9079,  0.5120],
        [-0.1605,  1.4328,  1.2876],
        [ 1.6723,  2.9140, -1.1098],
        [ 0.3744, -0.5117,  0.2893],
        [-0.9180,  0.9536,  0.9059]])


In [21]:
# more ways to do addition: syntax 2
print(torch.add(x, y))

tensor([[-0.8186,  1.9627,  0.1057],
        [ 0.1700,  2.5250,  1.4823],
        [-0.5873, -0.8884, -0.6335],
        [ 0.7094,  2.0470,  1.5691],
        [ 1.3990, -0.3599,  0.5338]])


In [22]:
# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.8186,  1.9627,  0.1057],
        [ 0.1700,  2.5250,  1.4823],
        [-0.5873, -0.8884, -0.6335],
        [ 0.7094,  2.0470,  1.5691],
        [ 1.3990, -0.3599,  0.5338]])


In [23]:
# Addition x to y 
# adds x to y
y.add_(x)
print(y)

tensor([[-0.8186,  1.9627,  0.1057],
        [ 0.1700,  2.5250,  1.4823],
        [-0.5873, -0.8884, -0.6335],
        [ 0.7094,  2.0470,  1.5691],
        [ 1.3990, -0.3599,  0.5338]])


In [24]:
# NOTE

# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

# You can use standard NumPy-like indexing with all bells and whistles!

print(x[:, 1])

tensor([ 1.1708,  2.1556, -1.6139,  1.3482, -1.1156])


In [25]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
# If you have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.0505])
-2.0504660606384277


In [27]:
# Read later:

# 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described here.
# NumPy Bridge
# Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

# The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [10]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [11]:
# CUDA Tensors  

# Tensors can be moved onto any device using the .to method.
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 0.9485, -1.7662,  0.8067],
        [-0.1136,  1.9000,  1.8919],
        [ 2.5397,  3.2545, -0.8473],
        [ 0.9253, -0.0172,  0.5908],
        [-0.1937,  1.0291,  1.2559]], device='cuda:0')
tensor([[ 0.9485, -1.7662,  0.8067],
        [-0.1136,  1.9000,  1.8919],
        [ 2.5397,  3.2545, -0.8473],
        [ 0.9253, -0.0172,  0.5908],
        [-0.1937,  1.0291,  1.2559]], dtype=torch.float64)
